# Generated by Django 4.0.5 on 2022-06-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tag', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=40)),
                ('temp', models.FloatField()),
                ('feels', models.FloatField()),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('pressure', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('visibility', models.IntegerField()),
                ('wind_speed', models.IntegerField()),
                ('wind_dir', models.IntegerField()),
                ('clouds', models.IntegerField()),
            ],
        ),
    ]
